# Generated by Django 5.0.6 on 2024-06-22 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('type', models.IntegerField(choices=[(1, 'todo'), (2, 'simple_note')])),
                ('state', models.IntegerField(choices=[(1, 'done'), (2, 'pause'), (3, 'doing'), (4, 'not_started')], default=4)),
                ('attachment', models.FileField(null=True, upload_to='upload/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.IntegerField(choices=[(1, 'done'), (2, 'pause'), (3, 'doing'), (4, 'not_started')], default=4)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.notebook')),
            ],
        ),
    ]
